add return value to Response.write
Pylons/webob pull request #422
Opened 2020-10-17 07:05 UTC by gjo

The `Response.body_file` is described as a file-like object. However, the `write` method does not return the wrote length.

2020-10-17 16:41 UTC, mmerickel commented
LGTM could you please add an entry to the changelog?

2020-10-18 08:56 UTC, stevepiercy requested changes
Grammar fix

2020-10-18 08:56 UTC, stevepiercy commented on CHANGES.txt
> +- ``Response.body_file.write`` and ``Response.write`` now returns the wrote
```suggestion
- ``Response.body_file.write`` and ``Response.write`` now returns the written
```

2020-10-18 13:41 UTC, stevepiercy approved these changes

2020-10-20 19:35 UTC, merged

2020-10-21 01:15 UTC, gjo commented
thx!